language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-lowest"
    # Test against Symfony LTS versions
    - php: 5.6
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.3
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.3
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.3.*"
    # Test against dev versions
    - php: 5.6
      env: DEPENDENCIES=dev
    - php: 7.3
      env: DEPENDENCIES=dev
  allow_failures:
    - env: DEPENDENCIES=dev

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi

install:
    - composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit -v --coverage-text
